interface = "test"

[qdiscs."root"]
type = "hfsc"
handle = "1:"
parent = "root"
  [qdiscs."root".specs]
  defCls = 1

[qdiscs."prio1"]
type = "fq_codel"
handle = "11:"
parent = "prio1"
  [qdiscs."prio1".specs]
	limit = 1200
	flow = 65535
	target = 5000
	ecn = 0

[qdiscs."prio2"]
type = "fq_codel"
handle = "12:"
parent = "prio2"
  [qdiscs."prio2".specs]
	limit = 1200
	flow = 65535
	target = 5000
	ecn = 0

[qdiscs."other"]
type = "fq_codel"
handle = "13:"
parent = "other"
  [qdiscs."other".specs]
	limit = 1200
	flow = 65535
	target = 5000
	ecn = 0

# max interface speed
[classes."interface"]
type = "hfsc"
classid = "1:1"
parent = "1:"
	[classes."interface".specs.sc]
	burst = 0.0
	delay = 0
	rate = 1e9
	[classes."interface".specs.ul]
	burst = 0.0
	delay = 0
	rate = 1e9

# reserved for interface comms
[classes."reservedComms"]
type = "hfsc"
classid = "1:3"
parent = "interface"
	[classes."reservedComms".specs.ls]
	burst = 0.0
	delay = 0
	rate = 20e6

# max internet speed
[classes."internet"]
type = "hfsc"
classid = "1:2"
parent = "interface"
	[classes."internet".specs.sc]
	burst = 0.0
	delay = 0
	rate = 200e6
	[classes."internet".specs.ul]
	burst = 0.0
	delay = 0
	rate = 200e6

# prio 1
[classes."prio1"]
type = "hfsc"
classid =  "1:11"
parent = "internet"
	[classes."prio1".specs.sc]
	burst = 0.0
	delay = 0
	rate = 100e6

# prio 2
[classes."prio2"]
type = "hfsc"
classid = "1:12"
parent = "internet"
	[classes."prio2".specs.sc]
	burst = 0.0
	delay = 60
	rate = 100e6

# other
[classes."other"]
type = "hfsc"
classid = "1:13"
parent = "internet"
	[classes."other".specs.ls]
	burst = 0.0
	delay = 100
	rate = 30e6
