interface = "test"

[qdiscs."root-qd"]
type = "hfsc"
handle = "1:0"
parent = "root"
        [qdiscs."root-qd".specs]
        defCls = 3

[qdiscs."prio1-qd"]
type = "fq_codel"
handle = "11:0"
parent = "prio1-cl"
        [qdiscs."prio1-qd".specs]
	limit = 1200
	flow = 65535
	target = 5000
	ecn = 0

[qdiscs."prio2-qd"]
type = "fq_codel"
handle = "12:0"
parent = "prio2-cl"
        [qdiscs."prio2-qd".specs]
	limit = 1200
	flow = 65535
	target = 5000
	ecn = 0

#[qdiscs."other-qd"]
#type = "fq_codel"
#handle = "13:0"
#parent = "other-cl"
#        [qdiscs."other-qd".specs]
#	limit = 1200
#	flow = 65535
#	target = 5000
#	ecn = 0

# max interface speed
[classes."interface-cl"]
type = "hfsc"
classid = "1:1"
parent = "root-qd"
	[classes."interface-cl".specs.sc]
	burst = 0.0
	delay = 0
	rate = 125e6
	[classes."interface-cl".specs.ul]
	burst = 0.0
	delay = 0
	rate = 125e6

# reserved for interface comms
[classes."reservedComms-cl"]
type = "hfsc"
classid = "1:3"
parent = "interface-cl"
	[classes."reservedComms-cl".specs.ls]
	burst = 0.0
	delay = 0
	rate = 25e5

# max internet speed
[classes."internet-cl"]
type = "hfsc"
classid = "1:2"
parent = "interface-cl"
	[classes."internet-cl".specs.sc]
	burst = 0.0
	delay = 0
	rate = 25e6
	[classes."internet-cl".specs.ul]
	burst = 0.0
	delay = 0
	rate = 25e6

# prio 1
[classes."prio1-cl"]
type = "hfsc"
classid =  "1:11"
parent = "internet-cl"
	[classes."prio1-cl".specs.sc]
	burst = 0.0
	delay = 0
	rate = 125e5

# prio 2
[classes."prio2-cl"]
type = "hfsc"
classid = "1:12"
parent = "internet-cl"
	[classes."prio2-cl".specs.sc]
	burst = 0.0
	delay = 60
	rate = 125e5

# other
#[classes."other-cl"]
#type = "hfsc"
#classid = "1:13"
#parent = "internet-cl"
#	[classes."other-cl".specs.ls]
#	burst = 0.0
#	delay = 100
#	rate = 375e4
